apiVersion: v2
name: short-service
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

appVersion: "1.16.0"
dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://./charts/frontend"
  - name: backend
    version: 0.1.0
    repository: "file://./charts/backend"
  - name: db
    version: 0.1.0
    repository: "file://./charts/db"
