apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-cluster-ip
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
  selector:
    components: {{ .Values.app.components }}
  